# nodeLinker: pnp
# packageExtensions:
#   "@nestjs/testing@*":
#     dependencies:
#       "@nestjs/common": "^10.4.15"
#       "@nestjs/core": "^10.4.15"
#       "@nestjs/platform-express": "^10.4.15"
#   "@nestjs/cache-manager@*":
#     dependencies:
#       keyv: "*"
#   typeorm@*:
#     peerDependencies:
#       "@nestjs/typeorm": "*"
#   cookie-parser@*:
#     peerDependencies:
#       "@types/cookie-parser": "*"

nodeLinker: node-modules

packageExtensions:
  "@nestjs/testing@*":
    dependencies:
      "@nestjs/common": "^10.4.15"
      "@nestjs/core": "^10.4.15"
      "@nestjs/platform-express": "^10.4.15"
  "@nestjs/cache-manager@*":
    dependencies:
      keyv: "*"
  "typeorm@*":
    peerDependencies:
      "@nestjs/typeorm": "*"
  "cookie-parser@*":
    peerDependencies:
      "@types/cookie-parser": "*"
  "@nestjs/core@*":
    dependencies:
      "reflect-metadata": "*"
  "@nestjs/common@*":
    dependencies:
      "reflect-metadata": "*"
  "cache-manager@*":
    peerDependencies:
      "@types/cache-manager": "*"
  "nodemailer@*":
    peerDependencies:
      "@types/nodemailer": "*"
